### ISSUE TITLE
Project specific configuration

### ISSUE THREAD

**Issue by dshafik** [jmolivas/phpqa#5]
It would be great if this looked for the configuration file within the current working directory (like box, phpunit, phpdox, etc) as well as supporting both `phpqa.yml` and `phpqa.yml.dist`.

This way I could specify the type of project, and what tools/config to use on a per-project basis.

**Comment by jmolivas** [comment]
@dshafik: Done may try updating project and test it again.

It supports both `phpqa.yml` and `phpqa.yml.dist`.

You can copy main config file https://github.com/jmolivas/phpqa/blob/master/config.yml and apply your changes or only set the values that you are trying to override, since the project load the main file and apply the one you have at your current working directory.

**Comment by jmolivas** [comment]
Once this is close I will work on https://github.com/jmolivas/phpqa/issues/6 

That one will ask where to copy, home-dir or current-dir ?

**Comment by jmolivas** [comment]
Once you have `phpqa.yml` or `phpqa.yml.dist`on your current directory, you just run it like:

```
$ phpqa analyze --files=src/
```
